### ISSUE TITLE
Allow specifying QuerySplitBehaviour for specifications

### ISSUE THREAD

**Issue by ConnerOrth** [ardalis/Specification.EFCore#1]
When retrieving one-to-many EFCore starting from v5 allows us to specify whether or not we want to execute the query as a single statement or as a split statement.
see: [MS docs on split-queries](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#split-queries)

Currently at the dbcontext-level we are able to set this globally.
Would like to be able to set this per specification.

What are your thoughts on this, @ardalis ?

**Comment by ardalis** [comment]
Seems like something that would be good to put in the specification, agreed.

I see this in the docs:

> Split queries can be enabled by placing the new AsSplitQuery operator anywhere in your LINQ query, or globally in your model's OnConfiguring. For further information, see the full documentation on split queries.

Which hopefully means this shouldn't be too difficult to add. What do you think @fiseni?

**Comment by fiseni** [comment]
We recently added support for AsNoTracking, and we can add for split queries too. But, first we have to decide how will we proceed with EF5. Either we'll have a separate plugin/addon package or will update the existing one to the latest version. There is a discussion [here](https://github.com/ardalis/Specification/pull/62#issuecomment-727235850)

As for the split-queries, that's an important topic, at least for anyone who wants to get in more depth and have more control over the executed queries. I was answering a question regarding this, I'm quoting part of it here too.

>How many Include statements are OK to have?

>While creating JOINs in SQL, the real issue is not about how many tables, but the cardinality. If the dependent tables are configured as one-to-one relationships, that's quite OK. But if you're including dependent tables, where there are many rows for each principal row, then it can have quite an impact on the performance. On top of that, you should be careful what SQL queries are being produced by EF as well. The EF Core 1&2 uses split queries, while EF Core 3 uses a single query. If you have a lot of 1:n relationships and use a single query, then you might end with a "cartesian explosion" (consider split queries in these cases).

<strong>Note</strong> This repository is no longer active and is not maintained. The `EFCore` plugin package is maintained in the main repo [here](https://github.com/ardalis/Specification). All Specification packages are maintained in that repo.

**Comment by ConnerOrth** [comment]
Thanks for the update.
I copied this ticket over to the mentioned repo, so closing this as a result of that move.
